// <auto-generated />
namespace ITMatcherWeb.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BulletinTypeadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BulletinTypeadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201805112014545_BulletinType added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
